[workspace]
authors = ["Clément NOBER <clement.nober@etu.minesparis.psl.eu>"]
channels = ["conda-forge"]
name = "altegrad"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.9"
pytorch = ">=2.4.0,<3"
ipykernel = ">=6.29.5,<7"
numpy = ">=1.24.4,<2"
matplotlib = ">=3.7.3,<4"
tqdm = ">=4.67.1,<5"
nltk = ">=3.9.1,<4"
jupyter = ">=1.1.1,<2"
notebook = ">=7.2.2,<8"
